package com.jarves.mh.data

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

interface SecretStore {
    fun put(providerId: String, secret: String)
    fun contains(providerId: String): Boolean
    fun remove(providerId: String)
    fun get(providerId: String): String?
}

class ApiKeyVault(context: Context) : SecretStore {
    private val preferences = context.getSharedPreferences("pocket_secrets", Context.MODE_PRIVATE)
    private val alias = "pocket-provider-key"

    override fun put(providerId: String, secret: String) {
        if (secret.isBlank()) return
        // nosemgrep:kotlin.lang.security.gcm-detection.gcm-detection - a fresh random IV is generated by the cipher itself and stored per entry ($providerId.iv); no static or reused IV.
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateKey())
        val encrypted = cipher.doFinal(secret.toByteArray(Charsets.UTF_8))
        preferences.edit()
            .putString("$providerId.iv", Base64.encodeToString(cipher.iv, Base64.NO_WRAP))
            .putString("$providerId.value", Base64.encodeToString(encrypted, Base64.NO_WRAP))
            .apply()
    }

    override fun contains(providerId: String): Boolean = preferences.contains("$providerId.value")

    override fun remove(providerId: String) {
        preferences.edit()
            .remove("$providerId.iv")
            .remove("$providerId.value")
            .apply()
    }

    override fun get(providerId: String): String? = runCatching {
        val iv = Base64.decode(preferences.getString("$providerId.iv", null), Base64.NO_WRAP)
        val encrypted = Base64.decode(preferences.getString("$providerId.value", null), Base64.NO_WRAP)
        // nosemgrep:kotlin.lang.security.gcm-detection.gcm-detection - the IV was stored next to the ciphertext at encryption time and is fed back here; no reuse across entries.
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.DECRYPT_MODE, getOrCreateKey(), GCMParameterSpec(128, iv)) // nosemgrep:kotlin.lang.security.gcm-detection.gcm-detection
        cipher.doFinal(encrypted).toString(Charsets.UTF_8)
    }.getOrNull()

    private fun getOrCreateKey(): SecretKey {
        val keyStore = KeyStore.getInstance("AndroidKeyStore").apply { load(null) }
        (keyStore.getKey(alias, null) as? SecretKey)?.let { return it }
        return KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, "AndroidKeyStore").run {
            init(
                KeyGenParameterSpec.Builder(alias, KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT)
                    .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    .build(),
            )
            generateKey()
        }
    }
}
